FROM alpine:3

LABEL author="Alvin Rig"
LABEL company="Pinnie Inc" website="https://www.linkedin.com/in/alvinrig/" 

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"